FROM python:3 

RUN sudo apt-get update
RUN sudo apt-get install -y nginx
CMD ["sudo", "service", "nginx", "start"]

#RUN pip install django==3.2
#COPY . . 
#RUN python manage.py migrate
#CMD ["python","manage.py","runserver","0.0.0.0:8001"]